import { Analytics } from "@vercel/analytics/react";
import React from "react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <title>GyoHeon's Blog</title>
        <meta name="description" content="GyoHeon's Blog" />
      </head>
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
